let Program = [
    {
        ProgramType: "Art",
        Cost: "Free" ,
        Deadline: "04-08-22" ,
        Link: "https://cronkite.asu.edu/community/high-school-programs/camps/" ,
     },
    {
    ProgramType: "Writing",
    Cost: "Free",
    Deadline: "04-08-22",
    Link: "https://cronkite.asu.edu/community/high-school-programs/camps/" ,
     },
{
    ProgramType: "Medicine",
    Cost: "Paid",
    Deadline: "02-26-22" ,
    Link: "https://simr.stanford.edu/program-information.html"
 },
{
    ProgramType: "Mathematics",
    Cost: "Paid",
    Deadline: "03-15-22",
    Link: "https://sumac.spcs.stanford.edu/sumac-about/ ",
 },
{
    ProgramType: "STEM ",
    Cost: "Free",
    Deadline: "01-10-22",
    Link: "https://mdibl.org/education/student-fellowships/high-school-summer-fellowship-applications/" ,
 },
{
    ProgramType: "STEM",
    Cost: "Free_with_stipend" ,
    Deadline: "11-01-22",
    Link: "https://navalsteminterns.us/seap",
 },
{
    ProgramType: "Humanities",
    Cost: "Free",
    Deadline: "10-30-22",
    Link: "https://www.civicsunplugged.org/fellowship",
 },
{
    ProgramType: "Reseach",
    Cost: "Paid",
    Deadline: "11-01-22",
    Link: "https://www.polygence.org/" ,
 },
{
    ProgramType: "Social Impact",
    Cost: "Paid",
    Deadline: "1-30-22",
    Link: "https://www.haraworld.com/about",
 },
{
    ProgramType: "Startup",
    Cost: "Paid",
    Deadline: "10-30-22",
    Link: "https://launchx.com/",
 },
{
    ProgramType: "Pre-College",
    Cost: "Paid",
    Deadline: "4-30-22",
    Link: "https://www.wm.edu/as/niahd/precol/apply-dates/index.php",
 },
{
    ProgramType: "Internship",
    Cost: "Free + Stipend",
    Deadline:"6-15-22",
    Link: "https://www.fredhutch.org/en/about/internships/summer-high-school-internship-program.html",
 },
{
    ProgramType: "Internship",
    Cost: "Free + Stipend",
    Deadline: "NA",
    Link: "https://careers.microsoft.com/students/us/ens",
 },
{
    ProgramType: "Pre-College",
    Cost: "Paid",
    Deadline: "8-30-22",
    Link:" https://summer.harvard.edu/high-school-programs/",
 },
{
    ProgramType: "Startup",
    Cost: "Paid",
    Deadline: "03-31-22",
    Link: "https://www.aaja.org/programs-and-initiatives/jcamp/",
 },
{
    ProgramType: "Pre-College",
    Cost: "Paid",
    Deadline: "02-21-22",
    Link: "https://precollege.nd.edu/summer-scholars-online/eligibility-application-requirements/",
 },
{
    ProgramType: "STEM",
    Cost: "Paid",
    Deadline: "04-21-22",
    Link: "https://wyse.engineering.illinois.edu/hs-summer-stem-research-programs/",
 },
{
    ProgramType: "Theatre",
    Cost: "Paid",
    Deadline: "10-10-22",
    Link: "https://summerdrama.utoronto.ca/",
 },
{
    ProgramType: "Business",
    Cost: "Paid",
    Deadline: "8-15-22",
    Link: "https://globalscholars.yale.edu/about",
 },
{
    ProgramType: "Business",
    Cost: "Paid",
    Deadline: '"NA"',
    Link: "https://internationalprograms.utoronto.ca/online-learning/perspectives-global-business/",
 },
{
    ProgramType: "Free",
    Cost: "Paid",
    Deadline: "1-21-22",
    Link: "https://www.broadinstitute.org/partnerships/education/k-12-outreach/broad-summer-scholars-program"  ,
 },
{
    ProgramType: "Pre-College",
    Cost: "Free",
    Deadline: "10-30-22",
    Link: "https://launchx.com/",
 },
{
    ProgramType: "Pre-College",
    Cost: "Paid",
    Deadline: "3-12-22",
    Link: "https://www.purdue.edu/mep/Pre-CollegePrograms/MITEAcademicBootCamp-Rising Seniors.html",
 },
{
    ProgramType: "Writing",
    Cost: "Free",
    Deadline: "10-30-22",
    Link: "https://psjp.princeton.edu/",
 },
{
    ProgramType: "Pre-College",
    Cost: "Free",
    Deadline: "NA",
    Link: "https://business.howard.edu/office-student-affairs/high-school-summer-enrichment-programs" ,
 },
]